// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeOjT8PTRZvuTZ6jy0Wh9PPIwiD7DgKl8',
    appId: '1:489495783515:web:3b21c1543c095a35eb377e',
    messagingSenderId: '489495783515',
    projectId: 'event-planning-32cff',
    authDomain: 'event-planning-32cff.firebaseapp.com',
    storageBucket: 'event-planning-32cff.firebasestorage.app',
    measurementId: 'G-STSET5HWTL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ0N1NTAQbXJD4XuMnoO8xyh8DGypJWTY',
    appId: '1:489495783515:android:37967a7df43b15a5eb377e',
    messagingSenderId: '489495783515',
    projectId: 'event-planning-32cff',
    storageBucket: 'event-planning-32cff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWOYTgQ1eicK0RqPbU6bFAWNhZWz8HfQk',
    appId: '1:489495783515:ios:a552125707e429e7eb377e',
    messagingSenderId: '489495783515',
    projectId: 'event-planning-32cff',
    storageBucket: 'event-planning-32cff.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWOYTgQ1eicK0RqPbU6bFAWNhZWz8HfQk',
    appId: '1:489495783515:ios:a552125707e429e7eb377e',
    messagingSenderId: '489495783515',
    projectId: 'event-planning-32cff',
    storageBucket: 'event-planning-32cff.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeOjT8PTRZvuTZ6jy0Wh9PPIwiD7DgKl8',
    appId: '1:489495783515:web:0206b322cee23514eb377e',
    messagingSenderId: '489495783515',
    projectId: 'event-planning-32cff',
    authDomain: 'event-planning-32cff.firebaseapp.com',
    storageBucket: 'event-planning-32cff.firebasestorage.app',
    measurementId: 'G-7QE487XNEH',
  );
}
